@base_url=http://localhost:8003

### find data by id
GET {{base_url}}/v1/m-user/1

### find data by page
GET {{base_url}}/v1/m-user?page=0&size=10

### create data
POST {{base_url}}/v1/m-user
Content-Type: application/json
Accept-Encoding: gzip

{
    "password": "P@ssw0rd",
    "roleId": 1,
    "biodataId": 1,
    "email": "abCQvlgM@example.org",
    "id": 1,
    "isDelete": false,
}

### update data
PUT {{base_url}}/v1/m-user
Content-Type: application/json
Accept-Encoding: gzip

{
    "id": 1,
    "password": "P@ssw0rd",
    "roleId": 1,
    "biodataId": 1,
    "email": "abCQvlgM@example.org",
    "id": 1,
    "isDelete": false,
}

### delete
DELETE {{base_url}}/v1/m-user/1